# Generated by Django 3.2.4 on 2021-07-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del edificio')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('tipo_edificio', models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial')], max_length=30, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=100, verbose_name='Propietario/a')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=100)),
                ('num_cuartos', models.IntegerField(verbose_name='Número de cuartos')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='ordenamiento.edificio')),
            ],
        ),
    ]
